"""add task manager fields and dependencies

Revision ID: 0b36ae7e7c90
Revises: 9ae5a6ca2950
Create Date: 2026-06-01 08:58:09.246321+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b36ae7e7c90'
down_revision: Union[str, None] = '9ae5a6ca2950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_dependencies',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('source_task_id', sa.UUID(), nullable=False),
    sa.Column('target_task_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type', sa.String(), nullable=True),
    sa.Column('condition_label', sa.String(), nullable=True),
    sa.Column('is_cross_phase', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['source_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('activity_types', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('activity_types', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('chat_document_links_chat_session_id_fkey'), 'chat_document_links', type_='foreignkey')
    op.drop_constraint(op.f('chat_document_links_document_id_fkey'), 'chat_document_links', type_='foreignkey')
    op.create_foreign_key(None, 'chat_document_links', 'chat_sessions', ['chat_session_id'], ['id'])
    op.create_foreign_key(None, 'chat_document_links', 'trial_documents', ['document_id'], ['id'])
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_chat_messages_session_id'), table_name='chat_messages')
    op.drop_constraint(op.f('chat_messages_session_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chat_sessions', ['session_id'], ['id'])
    op.alter_column('chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_constraint(op.f('chat_sessions_trial_id_fkey'), 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'trial_documents', ['document_id'], ['id'])
    op.alter_column('document_chunks_docling', 'page_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('document_chunks_docling', 'chunk_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('document_chunks_docling', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_chunks_embedding_large_hnsw', 'document_chunks_docling', ['embedding_large'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding_large': 'vector_cosine_ops'})
    op.drop_constraint(op.f('document_chunks_docling_document_id_fkey'), 'document_chunks_docling', type_='foreignkey')
    op.create_foreign_key(None, 'document_chunks_docling', 'trial_documents', ['document_id'], ['id'])
    op.alter_column('invitations', 'token',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('invitations', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(op.f('invitations_organization_id_fkey'), 'invitations', type_='foreignkey')
    op.create_foreign_key(None, 'invitations', 'organizations', ['organization_id'], ['id'])
    op.alter_column('members', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('idx_members_organization'), table_name='members')
    op.drop_constraint(op.f('members_organization_id_fkey'), 'members', type_='foreignkey')
    op.drop_constraint(op.f('members_profile_id_fkey'), 'members', type_='foreignkey')
    op.create_foreign_key(None, 'members', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'members', 'profiles', ['profile_id'], ['id'])
    op.alter_column('organizations', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'organizations', 'themison_admins', ['created_by'], ['id'])
    op.drop_constraint(op.f('patient_documents_patient_id_fkey'), 'patient_documents', type_='foreignkey')
    op.create_foreign_key(None, 'patient_documents', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'patient_documents', 'members', ['uploaded_by'], ['id'])
    op.alter_column('patient_visits', 'cost_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_patient_visits_patient'), table_name='patient_visits')
    op.drop_index(op.f('idx_patient_visits_trial'), table_name='patient_visits')
    op.drop_constraint(op.f('patient_visits_doctor_id_fkey'), 'patient_visits', type_='foreignkey')
    op.create_foreign_key(None, 'patient_visits', 'members', ['doctor_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'patient_visits', 'members', ['created_by'], ['id'])
    op.drop_index(op.f('idx_patients_organization'), table_name='patients')
    op.drop_constraint(op.f('patients_organization_id_fkey'), 'patients', type_='foreignkey')
    op.create_foreign_key(None, 'patients', 'organizations', ['organization_id'], ['id'])
    op.alter_column('profiles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('qa_repository', 'sources',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_foreign_key(None, 'qa_repository', 'members', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('response_folders', 'org_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('response_folders', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('responses_archived', 'org_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('responses_archived', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('responses_archived', 'question',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('responses_archived', 'answer',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('responses_archived', 'raw_data',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using="raw_data::json")
    op.drop_constraint(op.f('roles_organization_id_fkey'), 'roles', type_='foreignkey')
    op.create_foreign_key(None, 'roles', 'organizations', ['organization_id'], ['id'])
    op.alter_column('semantic_cache_responses', 'response_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('semantic_cache_responses', 'context_hash',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               nullable=False)
    op.add_column('tasks', sa.Column('phase_id', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('assigned_role', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('blocked_reason', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('blocked_since', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('order_in_phase', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('suggested_date', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('suggested_assignee', sa.String(), nullable=True))
    op.alter_column('tasks', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'todo'::text"))
    op.alter_column('tasks', 'priority',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('tasks_created_by_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('themison_admins_email_key'), 'themison_admins', type_='unique')
    op.alter_column('trial_activity_types', 'activity_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('trial_activity_types', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('trial_activity_types', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_trial_documents_trial'), table_name='trial_documents')
    op.drop_constraint(op.f('trial_documents_trial_id_fkey'), 'trial_documents', type_='foreignkey')
    op.alter_column('trial_members', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_foreign_key(None, 'trial_members_pending', 'members', ['invited_by'], ['id'])
    op.alter_column('trial_patients', 'cost_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('trial_patients', 'patient_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_trial_patients_patient'), table_name='trial_patients')
    op.drop_index(op.f('idx_trial_patients_trial'), table_name='trial_patients')
    op.drop_constraint(op.f('trial_patients_trial_id_fkey'), 'trial_patients', type_='foreignkey')
    op.drop_constraint(op.f('trial_patients_patient_id_fkey'), 'trial_patients', type_='foreignkey')
    op.create_foreign_key(None, 'trial_patients', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'trial_patients', 'trials', ['trial_id'], ['id'])
    op.create_foreign_key(None, 'trial_patients', 'members', ['assigned_by'], ['id'])
    op.alter_column('trials', 'budget_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('trials', 'visit_schedule_template',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_trials_organization'), table_name='trials')
    op.drop_constraint(op.f('trials_organization_id_fkey'), 'trials', type_='foreignkey')
    op.create_foreign_key(None, 'trials', 'organizations', ['organization_id'], ['id'])
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using="password::uuid")
    op.create_unique_constraint(None, 'users', ['email'])
    op.alter_column('visit_activities', 'activity_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('visit_activities', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.create_foreign_key(None, 'visit_documents', 'members', ['uploaded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visit_documents', type_='foreignkey')
    op.alter_column('visit_activities', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('visit_activities', 'activity_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'password',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'trials', type_='foreignkey')
    op.create_foreign_key(op.f('trials_organization_id_fkey'), 'trials', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_trials_organization'), 'trials', ['organization_id'], unique=False)
    op.alter_column('trials', 'visit_schedule_template',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('trials', 'budget_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(None, 'trial_patients', type_='foreignkey')
    op.drop_constraint(None, 'trial_patients', type_='foreignkey')
    op.drop_constraint(None, 'trial_patients', type_='foreignkey')
    op.create_foreign_key(op.f('trial_patients_patient_id_fkey'), 'trial_patients', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('trial_patients_trial_id_fkey'), 'trial_patients', 'trials', ['trial_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_trial_patients_trial'), 'trial_patients', ['trial_id'], unique=False)
    op.create_index(op.f('idx_trial_patients_patient'), 'trial_patients', ['patient_id'], unique=False)
    op.alter_column('trial_patients', 'patient_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('trial_patients', 'cost_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(None, 'trial_members_pending', type_='foreignkey')
    op.alter_column('trial_members', 'settings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_foreign_key(op.f('trial_documents_trial_id_fkey'), 'trial_documents', 'trials', ['trial_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_trial_documents_trial'), 'trial_documents', ['trial_id'], unique=False)
    op.alter_column('trial_activity_types', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('trial_activity_types', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('trial_activity_types', 'activity_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_unique_constraint(op.f('themison_admins_email_key'), 'themison_admins', ['email'], postgresql_nulls_not_distinct=False)
    op.create_foreign_key(op.f('tasks_created_by_fkey'), 'tasks', 'members', ['created_by'], ['id'])
    op.alter_column('tasks', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'priority',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'todo'::text"))
    op.alter_column('tasks', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('tasks', 'suggested_assignee')
    op.drop_column('tasks', 'suggested_date')
    op.drop_column('tasks', 'order_in_phase')
    op.drop_column('tasks', 'blocked_since')
    op.drop_column('tasks', 'blocked_reason')
    op.drop_column('tasks', 'assigned_role')
    op.drop_column('tasks', 'phase_id')
    op.alter_column('semantic_cache_responses', 'context_hash',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('semantic_cache_responses', 'response_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.create_foreign_key(op.f('roles_organization_id_fkey'), 'roles', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('responses_archived', 'raw_data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('responses_archived', 'answer',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('responses_archived', 'question',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('responses_archived', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('responses_archived', 'org_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('response_folders', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('response_folders', 'org_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'qa_repository', type_='foreignkey')
    op.alter_column('qa_repository', 'sources',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('profiles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.create_foreign_key(op.f('patients_organization_id_fkey'), 'patients', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_patients_organization'), 'patients', ['organization_id'], unique=False)
    op.drop_constraint(None, 'patient_visits', type_='foreignkey')
    op.drop_constraint(None, 'patient_visits', type_='foreignkey')
    op.create_foreign_key(op.f('patient_visits_doctor_id_fkey'), 'patient_visits', 'members', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_patient_visits_trial'), 'patient_visits', ['trial_id'], unique=False)
    op.create_index(op.f('idx_patient_visits_patient'), 'patient_visits', ['patient_id'], unique=False)
    op.alter_column('patient_visits', 'cost_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(None, 'patient_documents', type_='foreignkey')
    op.drop_constraint(None, 'patient_documents', type_='foreignkey')
    op.create_foreign_key(op.f('patient_documents_patient_id_fkey'), 'patient_documents', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.alter_column('organizations', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.create_foreign_key(op.f('members_profile_id_fkey'), 'members', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('members_organization_id_fkey'), 'members', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_members_organization'), 'members', ['organization_id'], unique=False)
    op.alter_column('members', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.create_foreign_key(op.f('invitations_organization_id_fkey'), 'invitations', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('invitations', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('invitations', 'token',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'document_chunks_docling', type_='foreignkey')
    op.create_foreign_key(op.f('document_chunks_docling_document_id_fkey'), 'document_chunks_docling', 'trial_documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_chunks_embedding_large_hnsw', table_name='document_chunks_docling', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding_large': 'vector_cosine_ops'})
    op.alter_column('document_chunks_docling', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_chunks_docling', 'chunk_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('document_chunks_docling', 'page_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('chat_sessions_trial_id_fkey'), 'chat_sessions', 'trials', ['trial_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_sessions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_session_id_fkey'), 'chat_messages', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'chat_document_links', type_='foreignkey')
    op.drop_constraint(None, 'chat_document_links', type_='foreignkey')
    op.create_foreign_key(op.f('chat_document_links_document_id_fkey'), 'chat_document_links', 'trial_documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('chat_document_links_chat_session_id_fkey'), 'chat_document_links', 'chat_sessions', ['chat_session_id'], ['id'], ondelete='CASCADE')
    op.alter_column('activity_types', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('activity_types', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_table('task_dependencies')
    # ### end Alembic commands ###
