"""add collaboration hub tables

Revision ID: a8f126cb30cc
Revises: 001
Create Date: 2026-05-20 08:21:52.292484+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8f126cb30cc'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('trial_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collaboration_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('trial_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('thread_type', sa.Text(), nullable=False),
    sa.Column('anchors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('ai_draft_summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thread_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('last_read_message_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['last_read_message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collaboration_thread_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['collaboration_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inbox_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('trial_id', sa.UUID(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('sender_name', sa.Text(), nullable=False),
    sa.Column('sender_email', sa.Text(), nullable=True),
    sa.Column('to_addresses', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('cc_addresses', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('labels', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('folder', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_starred', sa.Boolean(), nullable=False),
    sa.Column('related_thread_id', sa.UUID(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_thread_id'], ['collaboration_threads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direct_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('trial_id', sa.UUID(), nullable=True),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('activity_types', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('activity_types', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('activity_types', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('chat_document_links_document_id_fkey'), 'chat_document_links', type_='foreignkey')
    op.drop_constraint(op.f('chat_document_links_chat_session_id_fkey'), 'chat_document_links', type_='foreignkey')
    op.create_foreign_key(None, 'chat_document_links', 'chat_sessions', ['chat_session_id'], ['id'])
    op.create_foreign_key(None, 'chat_document_links', 'trial_documents', ['document_id'], ['id'])
    op.alter_column('chat_messages', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_chat_messages_session_id'), table_name='chat_messages')
    op.drop_constraint(op.f('chat_messages_session_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chat_sessions', ['session_id'], ['id'])
    op.add_column('chat_sessions', sa.Column('document_id', sa.UUID(), nullable=True))
    op.add_column('chat_sessions', sa.Column('document_name', sa.String(length=255), nullable=True))
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_constraint(op.f('chat_sessions_trial_id_fkey'), 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'trial_documents', ['document_id'], ['id'])
    op.alter_column('document_chunks_docling', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('document_chunks_docling', 'page_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('document_chunks_docling', 'chunk_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('document_chunks_docling', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index('idx_chunks_embedding_large_hnsw', 'document_chunks_docling', ['embedding_large'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding_large': 'vector_cosine_ops'})
    op.drop_constraint(op.f('document_chunks_docling_document_id_fkey'), 'document_chunks_docling', type_='foreignkey')
    op.create_foreign_key(None, 'document_chunks_docling', 'trial_documents', ['document_id'], ['id'])
    op.add_column('invitations', sa.Column('token', sa.Text(), nullable=False))
    op.alter_column('invitations', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('invitations', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('invitations', 'status',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('invitations', 'invited_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('invitations', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint(op.f('invitations_organization_id_fkey'), 'invitations', type_='foreignkey')
    op.create_foreign_key(None, 'invitations', 'organizations', ['organization_id'], ['id'])
    op.add_column('members', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('members', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('members', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('members', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_members_organization'), table_name='members')
    op.drop_constraint(op.f('members_organization_id_fkey'), 'members', type_='foreignkey')
    op.drop_constraint(op.f('members_profile_id_fkey'), 'members', type_='foreignkey')
    op.create_foreign_key(None, 'members', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'members', 'profiles', ['profile_id'], ['id'])
    op.add_column('organizations', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('organizations', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('organizations', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('organizations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('organizations', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('organizations', 'support_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.create_foreign_key(None, 'organizations', 'themison_admins', ['created_by'], ['id'])
    op.alter_column('patient_documents', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('patient_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('patient_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('patient_documents', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('patient_documents', 'is_latest',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint(op.f('patient_documents_patient_id_fkey'), 'patient_documents', type_='foreignkey')
    op.create_foreign_key(None, 'patient_documents', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'patient_documents', 'members', ['uploaded_by'], ['id'])
    op.alter_column('patient_visits', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('patient_visits', 'visit_type',
               existing_type=postgresql.ENUM('screening', 'baseline', 'follow_up', 'treatment', 'assessment', 'monitoring', 'adverse_event', 'unscheduled', 'study_closeout', 'withdrawal', name='visit_type_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('patient_visits', 'status',
               existing_type=postgresql.ENUM('scheduled', 'in_progress', 'completed', 'cancelled', 'no_show', 'rescheduled', name='visit_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('patient_visits', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('patient_visits', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('patient_visits', 'cost_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('idx_patient_visits_patient'), table_name='patient_visits')
    op.drop_index(op.f('idx_patient_visits_trial'), table_name='patient_visits')
    op.drop_constraint(op.f('patient_visits_doctor_id_fkey'), 'patient_visits', type_='foreignkey')
    op.create_foreign_key(None, 'patient_visits', 'members', ['created_by'], ['id'])
    op.create_foreign_key(None, 'patient_visits', 'members', ['doctor_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('patients', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('patients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('patients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('patients', 'country',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('patients', 'consent_signed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('patients', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_patients_organization'), table_name='patients')
    op.drop_constraint(op.f('patients_organization_id_fkey'), 'patients', type_='foreignkey')
    op.create_foreign_key(None, 'patients', 'organizations', ['organization_id'], ['id'])
    op.add_column('profiles', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('profiles', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('qa_repository', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('qa_repository', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('qa_repository', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('qa_repository', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('qa_repository', 'sources',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_foreign_key(None, 'qa_repository', 'members', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('response_folders', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('response_folders', 'org_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('response_folders', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('response_folders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('response_folders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('responses_archived', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('responses_archived', 'org_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('responses_archived', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('responses_archived', 'question',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('responses_archived', 'answer',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('responses_archived', 'raw_data',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('responses_archived', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('responses_archived', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('roles', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('roles', 'permission_level',
               existing_type=postgresql.ENUM('read', 'edit', 'admin', name='permission_level'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint(op.f('roles_organization_id_fkey'), 'roles', type_='foreignkey')
    op.create_foreign_key(None, 'roles', 'organizations', ['organization_id'], ['id'])
    op.alter_column('semantic_cache_responses', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('semantic_cache_responses', 'response_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('semantic_cache_responses', 'hit_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('semantic_cache_responses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('semantic_cache_responses', 'last_accessed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('semantic_cache_responses', 'context_hash',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               nullable=False)
    op.alter_column('tasks', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint(op.f('tasks_created_by_fkey'), 'tasks', type_='foreignkey')
    op.alter_column('themison_admins', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('themison_admins', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('themison_admins', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint(op.f('themison_admins_email_key'), 'themison_admins', type_='unique')
    op.alter_column('trial_activity_types', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('trial_activity_types', 'activity_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('trial_activity_types', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('trial_activity_types', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('trial_activity_types', 'is_custom',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.add_column('trial_documents', sa.Column('ingestion_status', sa.Text(), nullable=True))
    op.alter_column('trial_documents', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('trial_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('trial_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('trial_documents', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('trial_documents', 'is_latest',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_trial_documents_trial'), table_name='trial_documents')
    op.drop_constraint(op.f('trial_documents_trial_id_fkey'), 'trial_documents', type_='foreignkey')
    op.alter_column('trial_members', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('trial_members', 'start_date',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('trial_members', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('trial_members', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('trial_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('trial_members_pending', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('trial_members_pending', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.create_foreign_key(None, 'trial_members_pending', 'members', ['invited_by'], ['id'])
    op.alter_column('trial_patients', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('trial_patients', 'enrollment_date',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('trial_patients', 'status',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('trial_patients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('trial_patients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('trial_patients', 'cost_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('trial_patients', 'patient_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('idx_trial_patients_patient'), table_name='trial_patients')
    op.drop_index(op.f('idx_trial_patients_trial'), table_name='trial_patients')
    op.drop_constraint(op.f('trial_patients_trial_id_fkey'), 'trial_patients', type_='foreignkey')
    op.drop_constraint(op.f('trial_patients_patient_id_fkey'), 'trial_patients', type_='foreignkey')
    op.create_foreign_key(None, 'trial_patients', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'trial_patients', 'members', ['assigned_by'], ['id'])
    op.create_foreign_key(None, 'trial_patients', 'trials', ['trial_id'], ['id'])
    op.alter_column('trials', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('trials', 'status',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('trials', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('trials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('trials', 'budget_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('trials', 'visit_schedule_template',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('idx_trials_organization'), table_name='trials')
    op.drop_constraint(op.f('trials_organization_id_fkey'), 'trials', type_='foreignkey')
    op.create_foreign_key(None, 'trials', 'organizations', ['organization_id'], ['id'])
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'users', ['email'])
    op.alter_column('visit_activities', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('visit_activities', 'activity_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('visit_activities', 'status',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('visit_activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('visit_activities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('visit_documents', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('visit_documents', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('visit_documents', 'is_latest',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('visit_documents', 'upload_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('visit_documents', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=True)
    op.alter_column('visit_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('visit_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.create_foreign_key(None, 'visit_documents', 'members', ['uploaded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visit_documents', type_='foreignkey')
    op.alter_column('visit_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('visit_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('visit_documents', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'USD'::character varying"),
               existing_nullable=True)
    op.alter_column('visit_documents', 'upload_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('visit_documents', 'is_latest',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('visit_documents', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('visit_documents', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.alter_column('visit_activities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('visit_activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('visit_activities', 'status',
               existing_type=sa.String(),
               server_default=sa.text("'pending'::text"),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('visit_activities', 'activity_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('visit_activities', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'password',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_constraint(None, 'trials', type_='foreignkey')
    op.create_foreign_key(op.f('trials_organization_id_fkey'), 'trials', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_trials_organization'), 'trials', ['organization_id'], unique=False)
    op.alter_column('trials', 'visit_schedule_template',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('trials', 'budget_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('trials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('trials', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('trials', 'status',
               existing_type=sa.TEXT(),
               server_default=sa.text("'planning'::text"),
               existing_nullable=True)
    op.alter_column('trials', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_constraint(None, 'trial_patients', type_='foreignkey')
    op.drop_constraint(None, 'trial_patients', type_='foreignkey')
    op.drop_constraint(None, 'trial_patients', type_='foreignkey')
    op.create_foreign_key(op.f('trial_patients_patient_id_fkey'), 'trial_patients', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('trial_patients_trial_id_fkey'), 'trial_patients', 'trials', ['trial_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_trial_patients_trial'), 'trial_patients', ['trial_id'], unique=False)
    op.create_index(op.f('idx_trial_patients_patient'), 'trial_patients', ['patient_id'], unique=False)
    op.alter_column('trial_patients', 'patient_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('trial_patients', 'cost_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('trial_patients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('trial_patients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('trial_patients', 'status',
               existing_type=sa.TEXT(),
               server_default=sa.text("'enrolled'::text"),
               existing_nullable=True)
    op.alter_column('trial_patients', 'enrollment_date',
               existing_type=sa.DATE(),
               server_default=sa.text('CURRENT_DATE'),
               existing_nullable=True)
    op.alter_column('trial_patients', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_constraint(None, 'trial_members_pending', type_='foreignkey')
    op.alter_column('trial_members_pending', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('trial_members_pending', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.alter_column('trial_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('trial_members', 'settings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('trial_members', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('trial_members', 'start_date',
               existing_type=sa.DATE(),
               server_default=sa.text('CURRENT_DATE'),
               existing_nullable=True)
    op.alter_column('trial_members', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_foreign_key(op.f('trial_documents_trial_id_fkey'), 'trial_documents', 'trials', ['trial_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_trial_documents_trial'), 'trial_documents', ['trial_id'], unique=False)
    op.alter_column('trial_documents', 'is_latest',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('trial_documents', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('trial_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('trial_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('trial_documents', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_column('trial_documents', 'ingestion_status')
    op.alter_column('trial_activity_types', 'is_custom',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('trial_activity_types', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('trial_activity_types', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('trial_activity_types', 'activity_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('trial_activity_types', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_unique_constraint(op.f('themison_admins_email_key'), 'themison_admins', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('themison_admins', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('themison_admins', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('themison_admins', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_foreign_key(op.f('tasks_created_by_fkey'), 'tasks', 'members', ['created_by'], ['id'])
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('tasks', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'priority',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.String(),
               server_default=sa.text("'todo'::text"),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('semantic_cache_responses', 'context_hash',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('semantic_cache_responses', 'last_accessed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('semantic_cache_responses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('semantic_cache_responses', 'hit_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('semantic_cache_responses', 'response_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('semantic_cache_responses', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.create_foreign_key(op.f('roles_organization_id_fkey'), 'roles', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('roles', 'permission_level',
               existing_type=postgresql.ENUM('read', 'edit', 'admin', name='permission_level'),
               server_default=sa.text("'read'::permission_level"),
               existing_nullable=False)
    op.alter_column('roles', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.alter_column('responses_archived', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('responses_archived', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('responses_archived', 'raw_data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('responses_archived', 'answer',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('responses_archived', 'question',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('responses_archived', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('responses_archived', 'org_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('responses_archived', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.alter_column('response_folders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('response_folders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('response_folders', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('response_folders', 'org_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('response_folders', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_constraint(None, 'qa_repository', type_='foreignkey')
    op.alter_column('qa_repository', 'sources',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('qa_repository', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('qa_repository', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('qa_repository', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('qa_repository', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.alter_column('profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('profiles', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_column('profiles', 'is_active')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.create_foreign_key(op.f('patients_organization_id_fkey'), 'patients', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_patients_organization'), 'patients', ['organization_id'], unique=False)
    op.alter_column('patients', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('patients', 'consent_signed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('patients', 'country',
               existing_type=sa.TEXT(),
               server_default=sa.text("'United States'::text"),
               existing_nullable=True)
    op.alter_column('patients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('patients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('patients', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_constraint(None, 'patient_visits', type_='foreignkey')
    op.drop_constraint(None, 'patient_visits', type_='foreignkey')
    op.create_foreign_key(op.f('patient_visits_doctor_id_fkey'), 'patient_visits', 'members', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_patient_visits_trial'), 'patient_visits', ['trial_id'], unique=False)
    op.create_index(op.f('idx_patient_visits_patient'), 'patient_visits', ['patient_id'], unique=False)
    op.alter_column('patient_visits', 'cost_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('patient_visits', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('patient_visits', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('patient_visits', 'status',
               existing_type=postgresql.ENUM('scheduled', 'in_progress', 'completed', 'cancelled', 'no_show', 'rescheduled', name='visit_status_enum'),
               server_default=sa.text("'scheduled'::visit_status_enum"),
               existing_nullable=False)
    op.alter_column('patient_visits', 'visit_type',
               existing_type=postgresql.ENUM('screening', 'baseline', 'follow_up', 'treatment', 'assessment', 'monitoring', 'adverse_event', 'unscheduled', 'study_closeout', 'withdrawal', name='visit_type_enum'),
               server_default=sa.text("'follow_up'::visit_type_enum"),
               existing_nullable=False)
    op.alter_column('patient_visits', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_constraint(None, 'patient_documents', type_='foreignkey')
    op.drop_constraint(None, 'patient_documents', type_='foreignkey')
    op.create_foreign_key(op.f('patient_documents_patient_id_fkey'), 'patient_documents', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.alter_column('patient_documents', 'is_latest',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('patient_documents', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('patient_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('patient_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('patient_documents', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.alter_column('organizations', 'support_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('organizations', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('organizations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('organizations', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('organizations', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_column('organizations', 'is_active')
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.create_foreign_key(op.f('members_profile_id_fkey'), 'members', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('members_organization_id_fkey'), 'members', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_members_organization'), 'members', ['organization_id'], unique=False)
    op.alter_column('members', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('members', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('members', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_column('members', 'is_active')
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.create_foreign_key(op.f('invitations_organization_id_fkey'), 'invitations', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('invitations', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("(now() + '7 days'::interval)"),
               existing_nullable=True)
    op.alter_column('invitations', 'invited_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('invitations', 'status',
               existing_type=sa.TEXT(),
               server_default=sa.text("'pending'::text"),
               existing_nullable=True)
    op.alter_column('invitations', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('invitations', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_column('invitations', 'token')
    op.drop_constraint(None, 'document_chunks_docling', type_='foreignkey')
    op.create_foreign_key(op.f('document_chunks_docling_document_id_fkey'), 'document_chunks_docling', 'trial_documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_chunks_embedding_large_hnsw', table_name='document_chunks_docling', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding_large': 'vector_cosine_ops'})
    op.alter_column('document_chunks_docling', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('document_chunks_docling', 'chunk_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('document_chunks_docling', 'page_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('document_chunks_docling', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('chat_sessions_trial_id_fkey'), 'chat_sessions', 'trials', ['trial_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('chat_sessions', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_column('chat_sessions', 'document_name')
    op.drop_column('chat_sessions', 'document_id')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_session_id_fkey'), 'chat_messages', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('chat_messages', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_constraint(None, 'chat_document_links', type_='foreignkey')
    op.drop_constraint(None, 'chat_document_links', type_='foreignkey')
    op.create_foreign_key(op.f('chat_document_links_chat_session_id_fkey'), 'chat_document_links', 'chat_sessions', ['chat_session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('chat_document_links_document_id_fkey'), 'chat_document_links', 'trial_documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.alter_column('activity_types', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('activity_types', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('activity_types', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_table('direct_messages')
    op.drop_table('inbox_messages')
    op.drop_table('collaboration_thread_messages')
    op.drop_table('thread_participants')
    op.drop_table('collaboration_threads')
    op.drop_table('chat_threads')
    # ### end Alembic commands ###
